#Instead of using TAB for indentation, use two spaces at the place of one TAB

#Controller to control robot legs, joint1&2 belongs to right leg, joint3&4 belongs to left leg.
robot_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  # joints: [joint1, joint2, joint3, joint4]
  joints: [joint3, joint4]

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
